#config.yaml

DATASET:
    base_path: '/kaggle/input/ht21-dataset/'
    train: 'NFL_Train.txt'
    valid: 'NFL_Test.txt'
    benchmark: 'Combined'
    mean_std: [[117, 110, 105], [67.10, 65.45, 66.23]]
    min_size: 720
    max_size: 1280

TRAINING:
    exp_name: 'NFL_R50'
    backbone : 'resnet50'
    only_backbone : False
    pretrained_model: '/kaggle/working/FT_R50_epoch_24.pth'
    save_dir: './exp/'
    start_epoch: 1
    eval_every: 100
    log_dir: './Logs/'
    milestones: [5, 10, 15]
    max_epoch: 20

HYPER_PARAM:
    learning_rate: 0.001
    momentum: 0.9
    weight_decay: 0.0005
    gamma: 0.5
    batch_size: 2

NETWORK:
    use_deform: False
    ohem: True
    context: 'cpm'
    custom_sampling: False
    soft_nms: False
    upscale_rpn: False
    median_anchors: True
